### ISSUE TITLE
Mod not showing in GD Launcher

### ISSUE THREAD

**Issue by MerlinBlatterer** [TrueHorse/Wild-Tool-Access#13]
I'm using GDLauncher for Minecraft. You can easily make your own modpacks, by searching for the mod and clicking install.
When going Right Click > Manage > Mods > Add Mod and clicking the Install Button, it says "Mod Not Available".
Also it doesn't load on forge 44.2.17 i guess.

**Comment by TrueHorse** [comment]
Thank you for sharing the details and not just going: "Öh. Doesn't work."
The reason, it is not working is, that this mod is only written for the Fabric mod loader, because I don't know how Forge works and there are currently a lot of things I am more up for, than learning it.
If you don't want to use Fabric for what ever reason (e.g. because you want to use a Forge only mod), the only way you could get to use this mod in the foreseeable future, is that someone else is going to port it or PatchworkMC picks up steam again (which is not happening for a while, because the main developer stated that he will focus on Quilt for now). Sorry.
