### ISSUE TITLE
Add option to remove empty slot at the start of the bars 

### ISSUE THREAD

**Issue by Timongcraft** [TrueHorse/Wild-Tool-Access#14]
This is a awesome mod, thank you very much!

But if have some ideas that would be nice if you implement them:

1. That if you open a bar it doesn't spart with a empty slot and the slot with the current item is selected
2. That you can do multiple things in the bars item selections by seperating them with a comma
Edit: 3. That if you have a bar open you can use the normal 1-9 keys to directly choose an item

And I have found one small bugs I wanted to report:

The list when selecting items in a bar is going out of the screen (![image](https://github.com/TrueHorse/Wild-Tool-Access/assets/77288029/b1480da4-6200-475c-b797-0ce37a00bd7a))

**Comment by TrueHorse** [comment]
Thank you for the praise. :) Glad you enjoy it.
All three of your ideas sound like good and useful additions to me and at least the first two shouldn't be TO hard to implement either. There is still a decent chance that I will not work on them for a while, if ever, because I am currently not very motivated to work on my Minecraft mods. At least for the 2. idea you could use the wta-command from last update to achieve the same thing, if only for one bar.
Regarding the bug, the GUI for the config screen is entirely provided by [cloth config](https://www.curseforge.com/minecraft/mc-mods/cloth-config), so I can't do anything about that.
But thank you that you go through the effort of providing feedback and ideas and report bugs. Having people like you is always very helpful when working on a project.

PS:
I hope you don't mind if I split your ideas up in separate issues. ;)
