### ISSUE TITLE
Some settings not working as intended 

### ISSUE THREAD

**Issue by Felisinnn** [TrueHorse/Wild-Tool-Access#21]
At least two of the options are not working: leadingEmptyslot set to false still displays the first slot as empty, and heldItemSelected set to true does not work for me either.  
I've tried changing the setting through ModMenu as well as through the config file but nothings seems to change. 

I'm not sure what information would be relevant for this: 
Version: Wild Tool Access 1.20 - 1.4.0 
Loader: Fabric Loader 0.14.24
Minecraft 1.20.1 

Mod list: 
-
![Captura de pantalla 2023-11-12 221845](https://github.com/TrueHorse/Wild-Tool-Access/assets/150624164/d2d9c297-f843-4ab1-8a18-771acb402263)
![Captura de pantalla 2023-11-12 221803](https://github.com/TrueHorse/Wild-Tool-Access/assets/150624164/9ec2e2ff-a22b-4da4-966c-440922ae1ae8)

**Comment by TrueHorse** [comment]
Thank you for the detailed report. I will look into it. :)

**Comment by TrueHorse** [comment]
Aaaawwsome. 🙂 Thank you again for making the effort to report all of this.
From the error it looks like its caused by my "sticky key" implementation for toggleMode.
I will look into that as well. For the other two I already identified what causes them not to work, but I don't know yet when I will work on fixing them and reward you for your efforts with a new version.
