### ISSUE TITLE
Add support for custom tools?

### ISSUE THREAD

**Issue by hatkidchan** [TrueHorse/Wild-Tool-Access#23]
Currently as I can tell you can only change second "stuff" hotbar. However, some mods add custom tools (examples: Wrench from Create, Network tool from AE2, etc). I couldn't find an option in the config to alter that and `/wta` command only lets you to change `stuff` set. Also, vanilla bow and fishing rod are apparently not part of the "tools" set?

**Comment by TrueHorse** [comment]
You should be able to change the content of the first bar by changing typeToAccess1.
If you want to have modded items in the first bar, you have to change it to stuff and the modded items to stuff, either manualy or using the command.
But yes, you can only change the content of stuff manualy, the others are more or less hard coded. To be specific, they contain all items that extend a certain Minecraft class, if that tells you anything. Sorry if not, but I don't know how I could explain it.
That is also the reason why the fishing rod is not in the "tools" type, because it doesn't extend ToolItem.
If you want a second changable type or all types changable you unfortunately have to ask someone else to fork this mod, because I will not have the time/motivation to work on it for a longer while. Sorry.
