### ISSUE TITLE
Add support for Mod Menu config editing

### ISSUE THREAD

**Issue by slovinsqui** [TrueHorse/Wild-Tool-Access#4]
mod menu compatibility?, is there a technical thingy that won't allow it to work?,
it would be neat if there was a way to customize keybinds, in my case, it would be great if I could use the extra buttons on my mouse

also what keys am I supposed to use to make de hotswap work, I can't find it anywhere lol

**Comment by TrueHorse** [comment]
What doesnt work with mod menu? Does it just crash instantly or is there functionality, that doesnt work?

You should be able to change your keybinds like any other keybind in the normal options menu.

What do you mean with hotswap?

**Comment by SinsOfVirtue** [comment]
You can change the keybinds for bringing up the two access menus in the options menu. But, you can't change the keybinds for scrolling through the items. I only bring this up because scrolling through the access menu's items doesn't work with mods like MidnightControl. Toggling the menu works, but not selecting an item.

A part of mod menu support that I would personally like to see is to have the config file options show in mod menu. Being able to select the distance between slots, position of the bar, and contents of the bars would be really nice.

Hope this helps!

**Comment by TrueHorse** [comment]
> You can change the keybinds for bringing up the two access menus in the options menu. But, you can't change the keybinds for scrolling through the items. I only bring this up because scrolling through the access menu's items doesn't work with mods like MidnightControl. Toggling the menu works, but not selecting an item.
> 
> A part of mod menu support that I would personally like to see is to have the config file options show in mod menu. Being able to select the distance between slots, position of the bar, and contents of the bars would be really nice.
> 
> Hope this helps!

Thank you for clearing that up and sorry for not answering for so long. I am currently working on the mod menu part and you should be able to scroll through the items like you scroll through the hotbar with the next MidnightControls update. (I made a merge request with a small change and it got accepted.)

**Comment by TrueHorse** [comment]
Mod Menu support is completed and will come with the next update.
